---
# Note: this secrets was created manually, values stored in Kubernetes cluster

# apiVersion: v1
# kind: Secret
# metadata:
#   name: bridge-liquidity-scheduler
#   namespace: default
#   labels:
#     app: bridge-liquidity-scheduler
#     environment: production
# type: Opaque
# data:
#   slack_webhook_url: "[secured]"
