---
apiVersion: v1
kind: Service
metadata:
  name: bridge-liquidity-scheduler
  namespace: default
  labels:
    app: bridge-liquidity-scheduler
    environment: production
spec:
  selector:
    app: bridge-liquidity-scheduler
    environment: production
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
